language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
notifications:
  slack:
    secure: hcg1soq1EwSpm0Z8mLFZyrrzYAAxT2bIa0I9Tl2P4vyfUsiEjOhCIw2+O01QEvlrM4SktDe6H2hN0y2E1C5xf880uat3L6MdQkd9U5mFX1o7oej/YCvtUcE6XhTGJ2yWs1kwPR0mNFr3GeT5s+bkJopFKgS55rJ90KHJ/6AdBfwgqwfIvGPbjJSJoYPpccdVtSgwNRmJXOi1KyH7du0tIbVGhn+Xj/fTPBsHbl8vRy2LEqWUQFy4lT4FyYbyctl0ByhSMbRtkD3/VReBZmtB59VDvvYqsJWEzS7+0IKaGBJjRtxJOAVfCmGH3FD9CfrhOtxJrNbMt4lCuNiSQWdaK6DsBJ4yosouwdPdzO7/9RFhAwak9U9m7JpdTR6RYekQYiExlHVn1vJ4p6BDUehXIIuY9/v+vyZkNB6z0o03q6ryqZrKY+4yBpAM039pevfNgdZXwdZXWHk2XHCP8pES8yYJWEP8TpenyeS9WvzqRtCcX18mxHlbI55xg8Vbi9WNUfQtxOWIayJtsEGB1P58a7s5Gc8DV4SX9RF1eIFrkICJdrS5yYQiz0/Pbxt0lVIn+9kTmb3xLygfPiJCReipG2gAzOFl4X9eyaz7fWD8NvwM7BFGEjLZ7z4EVskBnFELgNEmhOpiuZyeWMgUU3yhXOYDFY3uAUPmJPgdW8qs66g=
